#!/bin/bash
  if ! diff -q /tmp/haproxy.cfg /etc/haproxy/haproxy.cfg >&2
  then
    cat /tmp/haproxy.cfg > /etc/haproxy/haproxy.cfg
    if [[ -f /etc/init/haproxy.conf ]]
    then reload haproxy ## In case it switches to Upstart
    else /etc/init.d/haproxy reload
    fi
  fi

